//
//  SuggestItineraryViewController.m
//  Places
//
//  Created by Iris Fu on 8/11/22.
//

#import "SuggestItineraryViewController.h"
#import "ComposeItineraryViewController.h"
#import "PlaceTypeCell.h"

@interface SuggestItineraryViewController () <UITableViewDelegate, UITableViewDataSource, SaveAutogeneratedItineraryDelegate>
@property (nonatomic) UITapGestureRecognizer *tapRecognizer;
- (IBAction)didTapX:(id)sender;
@property (strong, nonatomic) IBOutlet UITextField *regionsField;
@property (strong, nonatomic) IBOutlet UITextField *numberOfDays;
@property (strong, nonatomic) IBOutlet UITextField *pace;
@property (strong, nonatomic) IBOutlet UITableView *placeTypesTableView;
@property (strong, nonatomic) NSArray *placeTypes;
@property (strong, nonatomic) NSMutableArray *selectedPlaceTypes;

@property (strong, nonatomic) Itinerary *autogeneratedItinerary;

@end

@implementation SuggestItineraryViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    self.tapRecognizer = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(didTapAnywhere:)];
    self.tapRecognizer.cancelsTouchesInView = NO;
    [self.view addGestureRecognizer:self.tapRecognizer];
    
    self.placeTypesTableView.delegate = self;
    self.placeTypesTableView.dataSource = self;
    self.placeTypesTableView.rowHeight = UITableViewAutomaticDimension;
    self.placeTypesTableView.allowsMultipleSelection = true;
    
    self.selectedPlaceTypes = [[NSMutableArray alloc]init];
    self.placeTypes = @[@"accounting",
                        @"airport",
                        @"amusement_park",
                        @"aquarium",
                        @"art_gallery",
                        @"atm",
                        @"bakery",
                        @"bank",
                        @"bar",
                        @"beauty_salon",
                        @"bicycle_store",
                        @"book_store",
                        @"bowling_alley",
                        @"bus_station",
                        @"cafe",
                        @"campground",
                        @"car_dealer",
                        @"car_rental",
                        @"car_repair",
                        @"car_wash",
                        @"casino",
                        @"cemetery",
                        @"church",
                        @"city_hall",
                        @"clothing_store",
                        @"convenience_store",
                        @"courthouse",
                        @"dentist",
                        @"department_store",
                        @"doctor",
                        @"drugstore",
                        @"electrician",
                        @"electronics_store",
                        @"embassy",
                        @"fire_station",
                        @"florist",
                        @"funeral_home",
                        @"furniture_store",
                        @"gas_station",
                        @"gym",
                        @"hair_care",
                        @"hardware_store",
                        @"hindu_temple",
                        @"home_goods_store",
                        @"hospital",
                        @"insurance_agency",
                        @"jewelry_store",
                        @"laundry",
                        @"lawyer",
                        @"library",
                        @"light_rail_station",
                        @"liquor_store",
                        @"local_government_office",
                        @"locksmith",
                        @"lodging",
                        @"meal_delivery",
                        @"meal_takeaway",
                        @"mosque",
                        @"movie_rental",
                        @"movie_theater",
                        @"moving_company",
                        @"museum",
                        @"night_club",
                        @"painter",
                        @"park",
                        @"parking",
                        @"pet_store",
                        @"pharmacy",
                        @"physiotherapist",
                        @"plumber",
                        @"police",
                        @"post_office",
                        @"primary_school",
                        @"real_estate_agency",
                        @"restaurant",
                        @"roofing_contractor",
                        @"rv_park",
                        @"school",
                        @"secondary_school",
                        @"shoe_store",
                        @"shopping_mall",
                        @"spa",
                        @"stadium",
                        @"storage",
                        @"store",
                        @"subway_station",
                        @"supermarket",
                        @"synagogue",
                        @"taxi_stand",
                        @"tourist_attraction",
                        @"train_station",
                        @"transit_station",
                        @"travel_agency",
                        @"university",
                        @"veterinary_care",
                        @"zoo"
    ];
}


#pragma mark - Table View
- (nonnull UITableViewCell *)tableView:(nonnull UITableView *)tableView cellForRowAtIndexPath:(nonnull NSIndexPath *)indexPath {
    PlaceTypeCell *cell = [tableView dequeueReusableCellWithIdentifier:@"PlaceTypeCell" forIndexPath:indexPath];
    NSString *type = self.placeTypes[indexPath.row];
    cell.type.text = type;
    return cell;
}

- (NSInteger)tableView:(nonnull UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return self.placeTypes.count;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [self.selectedPlaceTypes addObject:self.placeTypes[indexPath.row]];
}


#pragma mark - Navigation

- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    if ([segue.identifier isEqualToString:@"AutogenerateItinerarySegue"]) {
        NSString *region = self.regionsField.text;
        int days = [self.numberOfDays.text intValue];
        int placesPerDay = [self.pace.text intValue];
        int numPlacesToGenerate = days * placesPerDay;
        NSArray *selectedPlaceTypes = [self.selectedPlaceTypes copy];
        NSLog(@"Region: %@", region);
        NSLog(@"numPlacesToGenerate %d", numPlacesToGenerate);
        NSLog(@"selectedPlaceTypes %@", selectedPlaceTypes);
        
        // generate itinerary with given inputs
        self.autogeneratedItinerary = [Itinerary new];
        // set name
        self.autogeneratedItinerary.name = [NSString stringWithFormat:@"Autogenerated Itinerary for %@", [PFUser currentUser].username];
        // set dates
        NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
        dateFormatter.dateStyle = NSDateFormatterMediumStyle;
        dateFormatter.timeStyle = NSDateFormatterNoStyle;
        dateFormatter.locale = [[NSLocale alloc] initWithLocaleIdentifier:@"en_US"];
        self.autogeneratedItinerary.startDate = [dateFormatter stringFromDate:[NSDate date]];
        NSDate *endDate = [[NSCalendar currentCalendar] dateByAddingUnit:NSCalendarUnitDay value:days toDate:[NSDate date] options:0];
        self.autogeneratedItinerary.endDate = [dateFormatter stringFromDate:endDate];
        // set details
        self.autogeneratedItinerary.travelDetails = [NSString stringWithFormat:@"Consider taking a flight to %@", region];
        self.autogeneratedItinerary.lodgingDetails = [NSString stringWithFormat:@"A hotel or an Airbnb might be the move"];

        UINavigationController *navigationController = [segue destinationViewController];
        ComposeItineraryViewController *composeItineraryViewController = (ComposeItineraryViewController *)navigationController.topViewController;
        composeItineraryViewController.delegate = self.delegate; // delegate should be itinerary table view
        composeItineraryViewController.saveAutogeneratedDelegate = self;
        composeItineraryViewController.editingMode = YES;
        composeItineraryViewController.autogenerateForPlaceTypes = selectedPlaceTypes;
        composeItineraryViewController.itinerary = self.autogeneratedItinerary;
        composeItineraryViewController.region = region;
        composeItineraryViewController.numPlacesToGenerate = [NSNumber numberWithInt:numPlacesToGenerate];
    }
}

- (void)didTapAnywhere:(UITapGestureRecognizer *) sender {
    [self.view endEditing:YES];
}

- (void)didSaveAutogeneratedItinerary {
    [self dismissViewControllerAnimated:true completion:nil];
    [self.navigationController popViewControllerAnimated:YES];
}

- (IBAction)didTapX:(id)sender {
    [self dismissViewControllerAnimated:true completion:nil];
}

@end

